import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#003366',
    alignItems: 'center',
  },
  topImageContainer: {
    backgroundColor: '#FF0000',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 20,
  },
  carImage: {
    width: 180,
    height: 100,
    resizeMode: 'contain',
  },
  infoContainer: {
    backgroundColor: '#FFD700',
    padding: 20,
    borderRadius: 20,
    width: '85%',
    marginTop: 20,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 6,
    alignItems: 'center',
  },
  label: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
    fontFamily: 'sans-serif',
  },
  value: {
    backgroundColor: '#FF0000',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 10,
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    marginTop: 30,
  },
  editButton: {
    borderWidth: 2,
    borderColor: '#FFD700',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  deleteButton: {
    borderWidth: 2,
    borderColor: '#FFD700',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  buttonText: {
    color: '#FFD700',
    fontWeight: 'bold',
  },
  bottomMenu: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: '#003366',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  menuButton: {
    backgroundColor: '#003366',
    padding: 12,
    borderRadius: 30,
  },
  menuIcon: {
    width: 24,
    height: 24,
    tintColor: '#FFD700',
  },
  inputEditable: {
    backgroundColor: '#FFF',
    color: '#FF0000',
  },
});