import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#004AAD',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 80, 
  },
  card: {
    backgroundColor: '#FFD500',
    width: '90%',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    marginBottom: 140,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  imageContainer: {
    backgroundColor: '#EAEAEA',
    borderRadius: 10,
    padding: 20,
    marginBottom: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    alignItems: 'center',
  },
  image: {
    width: 60,
    height: 60,
  },
  imageInput: {
    width: '100%',
    backgroundColor: '#FFF',
    borderRadius: 10,
    height: 35,
    paddingHorizontal: 10,
    marginBottom: 15,
    color: '#000',
  },
  inputGroup: {
    width: '100%',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  label: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#FFF',
    width: 80,
  },
  input: {
    backgroundColor: 'red',
    borderRadius: 10,
    height: 25,
    flex: 1,
    paddingHorizontal: 8,
    color: '#FFF',
  },
  addButton: {
    backgroundColor: '#FFD500',
    borderRadius: 20,
    paddingHorizontal: 30,
    paddingVertical: 12,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  addButtonText: {
    fontWeight: 'bold',
    color: '#FFF',
    fontSize: 16,
  },
  bottomMenu: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: '#003366',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  menuButton: {
    backgroundColor: '#003366',
    padding: 12,
    borderRadius: 30,
  },
  menuIcon: {
    width: 24,
    height: 24,
    tintColor: '#FFD700',
  },
});